### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lecorguille**

### CODE REVIEW

**Comment by lecorguille** [comment]
@mtremblayfr
- There was a syntax error
- I also bump the version number

But ca, you propose a change log message?
https://github.com/workflow4metabolomics/nmr_bucketing/blob/36cfeddcfae53e1f3218ec87876bb9eb9f28e24d/galaxy/nmr_bucketing/NmrBucketing_xml.xml#L284

**Comment by lecorguille** [comment]
@mtremblayfr can you explain in one ou two sentence what those modifications are to feed the change log?
As you already do here : https://github.com/workflow4metabolomics/nmr_bucketing/blob/master/galaxy/nmr_bucketing/README.rst

**Comment by mtremblayfr** [comment]
Done

Marie Tremblay-Franco
New email : marie.tremblay-franco@inra.frmailto:marie.tremblay-franco@inra.fr

[cid:image001.png@01D238FD.68CB9720]

INRA, TOXALIM (Research Centre in Food Toxicology)
Platform MetaboHUB-MetaToul-AXIOM
180 Chemin de Tournefeuille
F-31027 TOULOUSE
France
+33 5 82 06 63 90

www.metatoul.fr http://www.metatoul.fr/
www.toulouse.inra.fr/axiomm http://www6.toulouse.inra.fr/axiomm
www.toulouse.inra.fr/toxalimhttp://www.toulouse.inra.fr/toxalim

De : Gildas Le Corguillé [mailto:notifications@github.com]
Envoyé : jeudi 17 novembre 2016 21:39
À : workflow4metabolomics/nmr_bucketing nmr_bucketing@noreply.github.com
Cc : Marie Tremblay-Franco marie.tremblay-franco@inra.fr; Mention mention@noreply.github.com
Objet : Re: [workflow4metabolomics/nmr_bucketing] Dev (#6)

@mtremblayfrhttps://github.com/mtremblayfr can you explain in one ou two sentence what those modifications are to feed the change log?
As you already do here : https://github.com/workflow4metabolomics/nmr_bucketing/blob/master/galaxy/nmr_bucketing/README.rst

**Comment by lecorguille** [comment]
@mtremblayfr Thanks
Even if you modified the master branch and not the Dev one. But maybe, I was not clear enough
I will merge and push to the TS ASAP

**Pull request merged**
